from classes.Chains import Networks


# GWEI CONTROL
MAX_GAS = 40

# TAKE THE WALLETS IN RANDOM ORDER
RANDOM_WALLETS = True

# REMOVE WALLET FROM FILES AFTER WORK
REMOVE_WALLET = True

# PROXY MODE
USE_PROXY = True

# THREADS CONTROLS
MAX_WORKERS = 4
WORKER_SLEEP_FROM = 40 # Seconds
WORKER_SLEEP_TO = 80 # Seconds

# SLEEPS AFTER WORK
SLEEP_AFTER_WORK_FROM = 60 # Seconds
SLEEP_AFTER_WORK_TO = 120 # Seconds

# BLOCKCHAIN SENDER (SELECT CLASS)
SEND_FROM = Networks.Arbitrum # Networks.(Chain) in chain insert your chain
